jx_git_url = "https://github.com/dineshtools/jx3-az-akv.git"
cluster_name = "dinesh-jx-lab"
cluster_resource_group_name="jx3aksrg"
apex_resource_group_name="jxdnsrg"
apex_domain_integration_enabled = true
apex_domain_name = "dineshpatil.net"
jx_bot_username = "dineshazpatil"
location = "eastus"
cluster_version = "1.20.13"
